services:
  mysql:
    image: mysql:8.4
    container_name: nextshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nextshopdb
      MYSQL_USER: nextshop
      MYSQL_PASSWORD: nextshop123
    ports:
      - "3307:3306"
    volumes:
      - nextshop_mysql_data:/var/lib/mysql

volumes:
  nextshop_mysql_data:
